### ISSUE TITLE
Open source code?

### ISSUE THREAD

**Issue by swzaaaaaaa** [LifeBeyondExpectations/PointMixer#1]
Thank you for your excellent work and look forward to your paper code.

**Comment by LifeBeyondExpectations** [comment]
Thank you. I will soon release the code.

**Comment by swzaaaaaaa** [comment]
When will you open the code, please?

**Comment by mayur-ag** [comment]
Any ETA on when the code will be out?

**Comment by haoranD** [comment]
Any ETA on when the code will be out? :)

**Comment by LifeBeyondExpectations** [comment]
Please refer to our new release, [ECCV22-PointMixer](https://github.com/LifeBeyondExpectations/ECCV22-PointMixer).
