### ISSUE TITLE
A question about the inter-set mixing

### ISSUE THREAD

**Issue by yifliu3** [LifeBeyondExpectations/PointMixer#3]
Great work!
I've read the paper and am confused about the inter-set mixing process. As the paper uses PointMixer to denote a universal mixing procedure, but this process described in Section3.3 uses relative position, while the inter-set mixing seems to contain the same points but perhaps different features, so does this mean the relative position used in inter-set mixing equals to zero? Thanks.

**Comment by LifeBeyondExpectations** [comment]
I am a bit confused with your qustion. Let me answer to your question in details.

> Q. 1
I checked that while we conduct inter-set mixing, the sum of the relative position is not zero. 

> Q. 2
" inter-set mixing seems to contain the same points but perhaps different features"
This is the exactly correct. 

> Q. 3
In our updated arxiv paper, you can refer to the detail of inter-set mixing with much simplifed explanation.
